# Generated by Django 5.2.6 on 2025-10-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asloj', '0004_contest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='created_by',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='participants',
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
