# Generated by Django 5.2.6 on 2025-10-12 06:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asloj', '0006_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='input_specification',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_specification',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
