# Generated by Django 5.2.6 on 2025-10-12 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asloj', '0007_alter_problem_input_specification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_file', models.FileField(upload_to='submissions/')),
                ('language', models.CharField(choices=[('py', 'Python'), ('c', 'C'), ('cpp', 'C++'), ('java', 'Java'), ('js', 'JavaScript')], max_length=10)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('RE', 'Runtime Error'), ('TLE', 'Time Limit Exceeded')], default='P', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='asloj.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
