# Generated by Django 5.2.6 on 2025-10-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asloj', '0009_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='problem',
            name='test_inputs',
            field=models.FileField(default=1, upload_to='problems/test_inputs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='test_outputs',
            field=models.FileField(default='exit', upload_to='problems/test_outputs'),
            preserve_default=False,
        ),
    ]
