# Generated by Django 5.2.6 on 2025-10-12 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asloj', '0010_remove_user_date_joined_problem_test_inputs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, default='media/pfp/default.jpeg', null=True, upload_to='media/pfp/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
