# Generated by Django 5.2.6 on 2025-10-12 13:34

import asloj.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asloj', '0011_user_pfp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='test_inputs',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='test_outputs',
        ),
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, default='pfp/default.jpeg', null=True, upload_to='pfp/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.CreateModel(
            name='TestInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=asloj.models.test_input_upload_to)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_inputs', to='asloj.problem')),
            ],
        ),
        migrations.CreateModel(
            name='TestOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=asloj.models.test_output_upload_to)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_outputs', to='asloj.problem')),
            ],
        ),
    ]
